### ISSUE TITLE
Module not found error

### ISSUE THREAD

**Issue by Papyrus61** [MattJeanes/Joystick-Module#13] opened 2019-12-23 12:52 UTC
ive been getting an error
Couldn't include file 'includes\modules\joystick.lua' (File not found) (@addons/github_sym_joystick_module/lua/autorun/client/joystick.lua (line 66))

[ERROR] addons/github_sym_joystick_module/lua/autorun/client/joystick.lua:66: Module not found!
  1. require - [C]:-1
   2. unknown - addons/github_sym_joystick_module/lua/autorun/client/joystick.lua:66

Couldn't include file 'includes\modules\joystick.lua' (File not found) (<nowhere>)

ive downloaded and added everything properly but I have no idea how to fix

**Comment by dvdvideo1234** [comment] 2020-06-18 12:04
Tell me if it is fixed in https://github.com/MattJeanes/Joystick-Module/pull/18

**Comment by MattJeanes** [comment] 2020-06-18 16:39
Hi there apologies for the delay in response must have missed this, according to your error message the DLL file could not be loaded, this can be caused by a few things:

- The file is not installed correctly into garrysmod/lua/bin folder, it must be in here not the addons folder
- You are running 64 bit gmod branch, this module doesn't yet have a compilation for 64 bit gmod
- The module installed doesn't match your OS or architecture, check out the naming and location section here for more info: https://wiki.facepunch.com/gmod/Creating_Binary_Modules

**Comment by MattJeanes** [comment] 2020-06-19 00:27
I've added in the 64 bit Windows and Linux updated binaries from https://github.com/thegrb93/StarfallEx and https://gitlab.h08.us/puff/joystick-module-linux here, hopefully this will help

**Comment by MattJeanes** [comment] 2020-09-16 09:59
Closing due to inactivity, hopefully your issue is resolved

**Closed by MattJeanes** 2020-09-16 09:59 UTC
